# Generated by Django 5.0.1 on 2024-03-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0002_alter_facture_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="reference",
            field=models.CharField(default="UqxKnIAm", max_length=120),
        ),
    ]
