# Generated by Django 5.0.1 on 2024-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0003_alter_facture_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="reference",
            field=models.CharField(default="HGpCY7cR", max_length=120),
        ),
    ]
