# Generated by Django 5.0.1 on 2024-03-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0005_alter_facture_reference_depense"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="beneficiaire",
            new_name="fournisseur",
        ),
        migrations.AlterField(
            model_name="facture",
            name="reference",
            field=models.CharField(default="5N1anGtJ", max_length=120),
        ),
    ]
