# Generated by Django 5.0.1 on 2024-01-19 13:16

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("anneescolaire", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=132)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                (
                    "ief",
                    models.CharField(
                        choices=[
                            ("Bignona1", "Bignona 1"),
                            ("Bignona2", "Bignona 2"),
                            ("Oussouye", "Oussouye"),
                            ("Ziguinchor", "Ziguinchor"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "type_etablissement",
                    models.CharField(
                        choices=[
                            ("Collège", "College"),
                            ("Lycée", "Lycee"),
                            ("Lycée Mixte", "Lycée Mixte"),
                            ("Autre", "Autre"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("nomce", models.CharField(blank=True, max_length=132, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "save_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Etablissement",
                "verbose_name_plural": "Etablissements",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=130)),
                ("effectif", models.IntegerField(default=0)),
                ("versement", models.IntegerField(default=0)),
                ("montant", models.IntegerField(default=0)),
                ("quote_date_time", models.DateTimeField(auto_now_add=True)),
                ("last_updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("is_ok", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="anneescolaire.anneescolaire",
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quoteparts",
                        to="etablissement.etablissement",
                    ),
                ),
                (
                    "save_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
    ]
