# Generated by Django 5.0.1 on 2024-01-22 00:47

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etablissement", "0003_alter_quote_annee_scolaire_alter_quote_etablissement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ief",
                "verbose_name_plural": "iefs",
            },
        ),
    ]
