# Generated by Django 5.0.1 on 2024-01-22 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etablissement", "0004_ief"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="ief",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="etablissement.ief",
            ),
        ),
    ]
