# Generated by Django 5.0.1 on 2024-01-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etablissement", "0006_alter_quote_annee_scolaire_alter_quote_etablissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="type_etablissement",
            field=models.CharField(
                choices=[
                    ("college", "College"),
                    ("Lycee", "Lycee"),
                    ("mixte", "Lycée Mixte"),
                    ("autre", "Autre"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
