# Generated by Django 5.0.1 on 2024-01-26 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anneescolaire", "0001_initial"),
        ("etablissement", "0008_alter_etablissement_type_etablissement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="ief",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etablissements",
                to="etablissement.ief",
            ),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="save_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etablissements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="annee_scolaire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="anneescolaire.anneescolaire",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="etablissement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="etablissement.etablissement",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="save_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
