# Generated by Django 5.0.1 on 2024-01-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etablissement", "0010_cotisation_alter_etablissement_ief_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mouvement",
                    models.CharField(
                        choices=[
                            ("Entree", "Entrée"),
                            ("Sortie", "Sortie"),
                            ("Regularisation", "Régularisation"),
                            ("Attente", "Attente"),
                        ],
                        default="Entree",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("montant", models.IntegerField(default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "save_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Cotisation",
        ),
    ]
