# Generated by Django 5.0.1 on 2024-01-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("etablissement", "0011_tresorerie_delete_cotisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tresorerie",
            name="save_by",
        ),
        migrations.AddField(
            model_name="tresorerie",
            name="content_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tresorerie",
            name="object_id",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="tresorerie",
            name="montant",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddIndex(
            model_name="tresorerie",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="etablisseme_content_b4949a_idx",
            ),
        ),
    ]
