# Generated by Django 5.0.1 on 2024-02-07 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "etablissement",
            "0012_remove_tresorerie_save_by_tresorerie_content_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="save_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etablissements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
