# Generated by Django 5.0.1 on 2024-02-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etablissement", "0013_alter_etablissement_save_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="ief",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etablissements",
                to="etablissement.ief",
            ),
        ),
    ]
