# Generated by Django 5.0.1 on 2024-02-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anneescolaire", "0001_initial"),
        ("etablissement", "0014_alter_etablissement_ief"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="annee_scolaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="anneescolaire.anneescolaire",
            ),
        ),
    ]
