# Generated by Django 5.0.1 on 2024-03-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etablissement", "0015_alter_quote_annee_scolaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="type_etablissement",
            field=models.CharField(
                choices=[
                    ("College", "Collège"),
                    ("Lycee", "Lycée"),
                    ("mixte", "Lycée Mixte"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=20,
                null=True,
            ),
        ),
    ]
