# Generated by Django 5.0.1 on 2024-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_first_name_user_name_remove_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
