# Generated by Django 5.0.1 on 2024-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
