# Generated by Django 5.0.1 on 2024-01-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_profile_username"),
        (
            "etablissement",
            "0009_alter_etablissement_ief_alter_etablissement_save_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="code_etablissement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eatblissement",
                to="etablissement.etablissement",
            ),
        ),
    ]
