# Generated by Django 5.0.1 on 2024-01-07 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ief", "0003_alter_ief_responsable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ief",
            name="responsable",
        ),
    ]
