# Generated by Django 5.0.1 on 2024-01-06 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ief", "0002_rename_created_by_ief_responsable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=16, null=True)),
                ("etablissement", models.CharField(max_length=132)),
                ("statut", models.CharField(blank=True, max_length=132, null=True)),
                ("nomce", models.CharField(blank=True, max_length=132, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mobile", models.CharField(blank=True, max_length=132, null=True)),
                ("fixe", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "conseiller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conseiller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ief",
                        to="ief.ief",
                    ),
                ),
            ],
            options={
                "verbose_name": "College",
                "verbose_name_plural": "Colleges",
            },
        ),
    ]
