# Generated by Django 5.0.1 on 2024-01-06 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("college", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="added_by",
            field=models.ForeignKey(
                default="30e7ee284acb47f0b47ebf25e79387d2",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="added_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
