# Generated by Django 5.0.1 on 2024-01-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("college", "0002_college_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="adresse",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
