# Generated by Django 5.0.1 on 2024-01-07 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("college", "0003_college_adresse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("annee_scolaire", models.CharField(default="2023-2024", max_length=9)),
                ("effectif", models.IntegerField(default=0)),
                ("versement", models.IntegerField(default=0)),
                ("montant", models.IntegerField(default=0)),
                ("quote_date_time", models.DateTimeField(auto_now_add=True)),
                ("last_updated_date", models.DateTimeField(blank=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("is_ok", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="college.college",
                    ),
                ),
                (
                    "save_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
    ]
