# Generated by Django 5.0.1 on 2024-01-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_alter_quote_college_alter_quote_save_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='annee_scolaire',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], max_length=9),
        ),
    ]
