# Generated by Django 5.0.1 on 2024-01-11 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_quote_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='annee_scolaire',
            field=models.CharField(choices=[('ALL', 'All'), ('2023-2024', 'Annee 2023 2024'), ('2024-2025', 'Annee 2024 2025'), ('2025-2026', 'Annee 2025 2026'), ('2026-2027', 'Annee 2026 2027'), ('2027-2028', 'Annee 2027 2028'), ('2028-2029', 'Annee 2028 2029'), ('2029-2030', 'Annee 2029 2030')], max_length=9),
        ),
        migrations.AlterField(
            model_name='quote',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='college.college'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
