# Generated by Django 5.0.1 on 2024-02-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="y00jpeCjxM", max_length=32),
        ),
    ]
