# Generated by Django 5.0.1 on 2024-02-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0002_alter_order_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="facture",
        ),
        migrations.AddField(
            model_name="article",
            name="facture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="commande.facture",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commande",
                to="commande.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="yv6wQZNek6", max_length=32),
        ),
    ]
