# Generated by Django 5.0.1 on 2024-03-01 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0003_remove_article_order_remove_order_facture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="commande.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="xx4F1RnEcR", max_length=32),
        ),
    ]
