# Generated by Django 5.0.1 on 2024-03-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0004_alter_facture_order_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="CPz4SpOjgF", max_length=32),
        ),
    ]
