# Generated by Django 5.0.1 on 2024-03-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0006_alter_facture_order_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="EEtc7IpVQ4", max_length=32),
        ),
    ]
