# Generated by Django 5.0.1 on 2024-03-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0010_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="8KVaGcaejD", max_length=32),
        ),
    ]
