# Generated by Django 5.0.1 on 2024-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0011_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="Xw79jGhsOf", max_length=32),
        ),
    ]
