# Generated by Django 5.0.1 on 2024-03-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0012_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="D84PCRR5dz", max_length=32),
        ),
    ]
