from account.models import User
from etablissement.models import Etablissement
from helpers.util import *
from django.core.management.base import BaseCommand
from django_extensions.db.fields import AutoSlugField


class Command(BaseCommand):
    help = 'Generate Etablissement'

    def add_arguments(self, parser):
        parser.add_argument('superuser', type=str, help='Create a superuser account')

    def handle(self, *args, **kwargs):
        superuser = kwargs['superuser']
        
        # name = "CEM IBRAHIMA SARRrrrrr"
        # slug = AutoSlugField(populate_from="name")
        # code = h_random_ascii(6)
        # ief = 1
        # type_etablissement = "college"
        # nomce = "Ibrahima Sarr"
        # email = "kisarr@kisarr.com"
        # phone = "77 554 41 91"
        # address = "Thiarrène"
        # save_by = 1
        
        etablissements = [
        {
            "id": 1,
            "name": "CEM Ahoune SANE",
            "slug": "cem-ahoune-sane",
            "code": "EUbxWm",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Germaine Gomis",
            "email": "cemas@gmail.com",
            "phone": "33 994 18 04",
            "address": "Bignona Commune",
            "created_at": "2024-01-19T19:46:55.777",
            "updated_at": "2024-01-19T19:46:55.777",
                "save_by": 1
        },
        {
            "id": 3,
            "name": "CEM Malick Fall",
            "slug": "cem-malick-fall",
            "code": "M@l1cK",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Sambou Ndour",
            "email": "malick@caosp.zig",
            "phone": "339911346",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T22:18:59.150",
            "updated_at": "2024-01-19T19:46:55.777",

                "save_by": 1
        },
        {
            "id": 5,
            "name": "Lycée Ahoune SANE",
            "slug": "lycee-ahoune-sane",
            "code": "L1c33@Sb",
            "ief": 1,
            "type_etablissement": "Lycée",
            "nomce": "Proviseur KABO",
            "email": "lasb@caosp.zig",
            "phone": "33 994 00 00",
            "address": "Bignona",
            "created_at": "2024-01-20T10:33:49.894",
            "updated_at": "2024-01-19T19:46:55.777",

                "save_by": 1
        },
        {
            "id": 6,
            "name": "CEM AHOUNE SANE",
            "slug": "cem-ahoune-sane",
            "code": "iE0HoAXl",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "ahoune.sane@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
                "save_by": 1
        },
        {
            "id": 7,
            "name": "CEM ARFANG BESSIRE SONKO",
            "slug": "cem-arfang-bessire-sonko",
            "code": "soeSMQZu",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "arfang.bessire.sonko@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        
        {
            "id": 8,
            "name": "CEM BADIOURE",
            "slug": "cem-badioure",
            "code": "FBKYgwge",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "badioure@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 9,
            "name": "CEM BAILA",
            "slug": "cem-baila",
            "code": "BElnGXJS",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "baila@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 10,
            "name": "CEM BRINDIAGO",
            "slug": "cem-brindiago",
            "code": "8HNuby9P",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "brindiago@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 11,
            "name": "CEM COUBALAN",
            "slug": "cem-coubalan",
            "code": "vwGCTUAd",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "coubalan@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 12,
            "name": "CEM COUBANAO",
            "slug": "cem-coubanao",
            "code": "iQnskHPL",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "coubanao@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 13,
            "name": "CEM DIANGO",
            "slug": "cem-diango",
            "code": "umPYOOnV",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "diango@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 14,
            "name": "CEM DJIBIDIONE",
            "slug": "cem-djibidione",
            "code": "XDFVvMxN",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "djibidione@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 15,
            "name": "CEM MAMPALAGO",
            "slug": "cem-mampalago",
            "code": "FMFqGE8c",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "mampalago@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 16,
            "name": "CEM NDIEBA",
            "slug": "cem-ndieba",
            "code": "BHGTTWmp",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "ndieba@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 17,
            "name": "CEM NIAMONE 1",
            "slug": "cem-niamone-1",
            "code": "qutUcyKB",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "niamone1@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 18,
            "name": "CEM NIAMONE 2",
            "slug": "cem-niamone-2",
            "code": "9gk0Byo5",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "niamone2@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 19,
            "name": "CEM NIANKITTE",
            "slug": "cem-niankitte",
            "code": "RtMPZVHg",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "niankitte@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 20,
            "name": "CEM OULAMPANE",
            "slug": "cem-oulampane",
            "code": "9zrAfoS5",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "oulampane@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 21,
            "name": "CEM OUONCK",
            "slug": "cem-ouonck",
            "code": "6b0ypd1A",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "ouonck@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 22,
            "name": "CEM SINDIAN",
            "slug": "cem-sindian",
            "code": "B3eTghu7",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "sindian@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 23,
            "name": "CEM SITOUKENE",
            "slug": "cem-sitoukene",
            "code": "tju3GX7w",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "sitoukene@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 24,
            "name": "CEM SORBONNE",
            "slug": "cem-sorbonne",
            "code": "H4AeI5Gp",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "sorbonne@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 25,
            "name": "CEM SOUDA",
            "slug": "cem-souda",
            "code": "PCZdtwns",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "souda@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 26,
            "name": "CEM SOUTOU",
            "slug": "cem-soutou",
            "code": "w9ioYDUa",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "soutou@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 27,
            "name": "CEM SUELLE",
            "slug": "cem-suelle",
            "code": "pK4auvBB",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "suelle@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 28,
            "name": "CEM TENDIEME",
            "slug": "cem-tendieme",
            "code": "HfLnB3Y2",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "tendieme@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 29,
            "name": "CEM TENGHORY ARR",
            "slug": "cem-tenghory-arr",
            "code": "bIMKC8EI",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "tenghory.arr@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 30,
            "name": "CEM TENGHORY TRANSG",
            "slug": "cem-tenghory-transg",
            "code": "qXZUspBm",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "tenghory.transg@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 31,
            "name": "CEM TOBOR",
            "slug": "cem-tobor",
            "code": "aRVoMzeh",
            "ief": 1,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "tobor@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 32,
            "name": "CEM ABENE",
            "slug": "cem-abene",
            "code": "X9N3P3aw",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "abene@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 33,
            "name": "CEM AFFINIAM",
            "slug": "cem-affiniam",
            "code": "m2K28vui",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "affiniam@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 34,
            "name": "CEM BADIANA",
            "slug": "cem-badiana",
            "code": "273Dnlvy",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "badiana@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 35,
            "name": "CEM BALINGORE",
            "slug": "cem-balingore",
            "code": "2Dozq9nA",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "balingore@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 36,
            "name": "CEM BANDJIKAKY",
            "slug": "cem-bandjikaky",
            "code": "CW4Ft9uZ",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "bandjikaky@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 37,
            "name": "CEM BARANLIR",
            "slug": "cem-baranlir",
            "code": "OziubkGp",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "baranlir@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 38,
            "name": "CEM BITI BITI",
            "slug": "cem-bitibiti",
            "code": "TJ4A46LA",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "bitibiti@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 39,
            "name": "CEM DARSALAM CHERIF",
            "slug": "cem-darsalam-cherif",
            "code": "WXFRllvG",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "darsalam.cherif@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 40,
            "name": "CEM DIANKI",
            "slug": "cem-dianki",
            "code": "cwrnNYod",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "dianki@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 41,
            "name": "CEM DIANNAH",
            "slug": "cem-diannah",
            "code": "BfbZDl6O",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "diannah@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 42,
            "name": "CEM DIATOCK",
            "slug": "cem-diatock",
            "code": "smcOhdpt",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "diatock@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 43,
            "name": "CEM DIEGOUNE",
            "slug": "cem-diegoune",
            "code": "lFsgeSdT",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "diegoune@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 44,
            "name": "CEM DIOULOULOU",
            "slug": "cem-diouloulou",
            "code": "y1cmmlXx",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "diouloulou@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 45,
            "name": "CEM DJINAKY",
            "slug": "cem-djinaky",
            "code": "aP3K3P8Y",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "djinaky@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 46,
            "name": "CEM DOMBONDIR",
            "slug": "cem-dombondir",
            "code": "TD2lEVQO",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "dombondir@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 47,
            "name": "CEM EFFOC",
            "slug": "cem-effoc",
            "code": "D09Dbgfa",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "effoc@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 48,
            "name": "CEM HILLOL",
            "slug": "cem-hillol",
            "code": "ui8rUlLk",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "hillol@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 49,
            "name": "CEM KABILINE 1",
            "slug": "cem-kabiline-1",
            "code": "hSbS1drJ",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kabiline1@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 50,
            "name": "CEM KABILINE 2",
            "slug": "cem-kabiline-2",
            "code": "eAb8gBD5",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kabiline2@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 51,
            "name": "CEM KAFOUNTINE",
            "slug": "cem-kafountine",
            "code": "H41fRwmh",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kafountine@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 52,
            "name": "CEM KAGNOBON",
            "slug": "cem-kagnobon",
            "code": "JuPOixfw",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kagnobon@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 53,
            "name": "CEM KARTIACK",
            "slug": "cem-kartiack",
            "code": "cwONKPWp",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kartiack@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 54,
            "name": "CEM KATABA 1",
            "slug": "cem-kataba-1",
            "code": "LgyU0Tnu",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kataba1@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 55,
            "name": "CEM KOUDIOUBE",
            "slug": "cem-koudioube",
            "code": "WrMl3c1y",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "koudioube@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 56,
            "name": "CEM MANDEGANE",
            "slug": "cem-mandegane",
            "code": "o2Et0lXT",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "mandegane@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 57,
            "name": "CEM MANGAGOULACK",
            "slug": "cem-mangagoulack",
            "code": "tHTsV3im",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "mangagoulack@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 58,
            "name": "CEM MLOMP BIGNONA",
            "slug": "cem-mlomp-bignona",
            "code": "EQ89Ql8S",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "mlomp.bignona@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 59,
            "name": "CEM NIOMOUNE",
            "slug": "cem-niomoune",
            "code": "J4SG9dU7",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "niomoune@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 60,
            "name": "CEM SANTHIABA",
            "slug": "cem-santhiaba",
            "code": "QNBndt0f",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "santhiaba@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 61,
            "name": "CEM SELETY",
            "slug": "cem-selety",
            "code": "NbvrYv9W",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "selety@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 62,
            "name": "CEM TENDOUCK",
            "slug": "cem-tendouck",
            "code": "ngD1HjhF",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "tendouck@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 63,
            "name": "CEM THIOBON",
            "slug": "cem-thiobon",
            "code": "iu8jOOPv",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "thiobon@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 64,
            "name": "CEM THIONCK ESSYL",
            "slug": "cem-thionck-essyl",
            "code": "5kPHgqhk",
            "ief": 2,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "thionck.essyl@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Bignona",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 65,
            "name": "CEM ALINE SITOE DIATTA",
            "slug": "cem-aline-sitoe-diatta",
            "code": "3eu2p0AE",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "aline.sitoe.diatta@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 66,
            "name": "CEM BOUCOTTE DIEMBERING",
            "slug": "cem-boucotte-diembering",
            "code": "kunDzIP2",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "boucotte.diembering@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 67,
            "name": "CEM BOUKITINGHO",
            "slug": "cem-boukitingho",
            "code": "pa400SkE",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "boukitingho@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 68,
            "name": "CEM CABROUSSE",
            "slug": "cem-cabrousse",
            "code": "pjYla3uc",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "cabrousse@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 69,
            "name": "CEM CAGNOUT",
            "slug": "cem-cagnout",
            "code": "l1HRZimJ",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "cagnout@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 70,
            "name": "CEM CAP SKIRRING",
            "slug": "cem-cap-skirring",
            "code": "XlAWkhch",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "cap.skirring@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 71,
            "name": "CEM CARABANE",
            "slug": "cem-carabane",
            "code": "yYmXuFeC",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "carabane@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 72,
            "name": "CEM DIEMBERING",
            "slug": "cem-diembering",
            "code": "NJAEomfO",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "diembering@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 73,
            "name": "CEM ELINKINE",
            "slug": "cem-elinkine",
            "code": "L9CAIDRS",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "elinkine@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 74,
            "name": "CEM LOUDIA OUOLOF",
            "slug": "cem-loudia-ouolof",
            "code": "cjkzW7nc",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "loudia.ouolof@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 75,
            "name": "CEM MLOMP OUSSOUYE",
            "slug": "cem-mlomp-oussouye",
            "code": "hisR6OZi",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "mlomp.oussouye@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 76,
            "name": "CEM OUKOUT",
            "slug": "cem-oukout",
            "code": "QGIemG7J",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "oukout@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 77,
            "name": "CEM OUSSOUYE 2",
            "slug": "cem-oussouye-2",
            "code": "CjYlSTza",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "oussouye2@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 78,
            "name": "CEM SIGANAR",
            "slug": "cem-siganar",
            "code": "vjh89TIo",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "siganar@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 79,
            "name": "CEM YOUTOU",
            "slug": "cem-youtou",
            "code": "lkwne5wC",
            "ief": 3,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "youtou@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 80,
            "name": "CEM ADEANE",
            "slug": "cem-adeane",
            "code": "TeA5mftG",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "adeane@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 81,
            "name": "CEM AGNACK",
            "slug": "cem-agnack",
            "code": "g2ZeBt5m",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "agnack@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 82,
            "name": "CEM BAGHAGHA",
            "slug": "cem-baghagha",
            "code": "kyaYHXkB",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "baghagha@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 83,
            "name": "CEM BOUCOTTE EST",
            "slug": "cem-boucotte-est",
            "code": "GoybmZ1m",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "boucotte.est@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 84,
            "name": "CEM BOUCOTTE SUD",
            "slug": "cem-boucotte-sud",
            "code": "gPaNmRCp",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "boucotte.sud@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 85,
            "name": "CEM BOUROFAYE",
            "slug": "cem-bourofaye",
            "code": "Ah49wo3K",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "bourofaye@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 86,
            "name": "CEM BOUTOUPA",
            "slug": "cem-boutoupa",
            "code": "NGJH2TkZ",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "boutoupa@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 87,
            "name": "CEM BOUTOUTE",
            "slug": "cem-boutoute",
            "code": "PmW9VQ8b",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "boutoute@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 88,
            "name": "CEM DIAGNON",
            "slug": "cem-diagnon",
            "code": "f4vPciGi",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "diagnon@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 89,
            "name": "CEM DIALANG",
            "slug": "cem-dialang",
            "code": "zdePlBwe",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "dialang@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 90,
            "name": "CEM DJIBONKER",
            "slug": "cem-djibonker",
            "code": "IzIqksA2",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "djibonker@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 91,
            "name": "CEM ENAMPORE",
            "slug": "cem-enampore",
            "code": "aogizblb",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "enampore@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 92,
            "name": "CEM GOUMEL",
            "slug": "cem-goumel",
            "code": "HPHpgnH5",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "goumel@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 93,
            "name": "CEM KAGNAROU",
            "slug": "cem-kagnarou",
            "code": "jGrdbkz1",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kagnarou@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 94,
            "name": "CEM KAGUITTE",
            "slug": "cem-kaguitte",
            "code": "vxHGxSl6",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kaguitte@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 95,
            "name": "CEM KANDE",
            "slug": "cem-kande",
            "code": "Xn1ef3Hf",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kande@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 96,
            "name": "CEM KANDE ALASSANE",
            "slug": "cem-kande-alassane",
            "code": "VgP8HrQb",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kande.alassane@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 97,
            "name": "CEM KANDIALANG",
            "slug": "cem-kandialang",
            "code": "INBD0mE2",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kandialang@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 98,
            "name": "CEM KENIA",
            "slug": "cem-kenia",
            "code": "BHGWvHmI",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "kenia@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 99,
            "name": "CEM LYNDIANE 1",
            "slug": "cem-lyndiane-1",
            "code": "BSCIIGPG",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "lyndiane1@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 100,
            "name": "CEM LYNDIANE 2",
            "slug": "cem-lyndiane-2",
            "code": "n7S2yj8Y",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "lyndiane2@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 101,
            "name": "CEM MALICK FALL",
            "slug": "cem-malick-fall",
            "code": "LFvCk9ZA",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "malick.fall@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 102,
            "name": "CEM MANGOULE",
            "slug": "cem-mangoule",
            "code": "VdxgmsZO",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "mangoule@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 103,
            "name": "CEM MEDJIEDJIE",
            "slug": "cem-medjiedjie",
            "code": "IC7O4Bv5",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "medjiedjie@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 104,
            "name": "CEM MPACK",
            "slug": "cem-mpack",
            "code": "Ga17TXcW",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "mpack@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 105,
            "name": "CEM NEMA II",
            "slug": "cem-nema-ii",
            "code": "e2gNIP6N",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "nema.ii@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 106,
            "name": "CEM NIAGUIS",
            "slug": "cem-niaguis",
            "code": "q1HrG4nS",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "niaguis@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 107,
            "name": "CEM NYASSIA",
            "slug": "cem-nyassia",
            "code": "rK2JQWNb",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "nyassia@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 108,
            "name": "CEM SOUCOUPAPAYE",
            "slug": "cem-soucoupapaye",
            "code": "EVMwapqv",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "soucoupapaye@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 109,
            "name": "CEM TETE DIADHIOU",
            "slug": "cem-tete-diadhiou",
            "code": "UPCS2f2d",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "tete.diadhiou@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 110,
            "name": "CEMT AMILCAR CABRAL",
            "slug": "cemt-amilcar-cabral",
            "code": "YlHvA1YN",
            "ief": 4,
            "type_etablissement": "college",
            "nomce": "Principal CEM",
            "email": "amilcar.cabral@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 112,
            "name": "LYCEE AHOUNE SANE",
            "slug": "lycee-ahoune-sane",
            "code": "rnCt4H3h",
            "ief": 1,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.ahoune.sane@caosp.zig",
            "phone": "33 991 11 59",
            "address": 1,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 114,
            "name": "LYCEE BAILA",
            "slug": "lycee-baila",
            "code": "WxPWdsmz",
            "ief": 1,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.baila@caosp.zig",
            "phone": "33 991 11 59",
            "address": 1,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 117,
            "name": "LYCEE COUBANAO",
            "slug": "lycee-coubanao",
            "code": "Gscn1Lp8",
            "ief": 1,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.coubanao@caosp.zig",
            "phone": "33 991 11 59",
            "address": 1,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 129,
            "name": "LYCEE OULAMPANE",
            "slug": "lycee-oulampane",
            "code": "zgSf0iBP",
            "ief": 1,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.oulampane@caosp.zig",
            "phone": "33 991 11 59",
            "address": 1,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 131,
            "name": "LYCEE SINDIAN",
            "slug": "lycee-sindian",
            "code": "OXVmdzf9",
            "ief": 1,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.sindian@caosp.zig",
            "phone": "33 991 11 59",
            "address": 1,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 133,
            "name": "LYCEE TENGHORY ARRONDISSEMENT",
            "slug": "lycee-tenghory-arrondissement",
            "code": "scLGzPgX",
            "ief": 1,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.tenghory.arrondissement@caosp.zig",
            "phone": "33 991 11 59",
            "address": 1,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 115,
            "name": "LYCEE BALINGORE",
            "slug": "lycee-balingore",
            "code": "kzMnphpL",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.balingore@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 118,
            "name": "LYCEE DAOUDA LAN CAMARA SANE",
            "slug": "lycee-daouda-lan-camara-sane",
            "code": "1Y3tde9b",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.daouda.lan.camara.sane@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 119,
            "name": "LYCEE DIOULOULOU",
            "slug": "lycee-diouloulou",
            "code": "R2uzhfzg",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.diouloulou@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 120,
            "name": "LYCEE DJIBIDIONE",
            "slug": "lycee-djibidione",
            "code": "VvnbuTNZ",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.djibidione@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 122,
            "name": "LYCEE DJINAKY",
            "slug": "lycee-djinaky",
            "code": "ApE3D4NZ",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.djinaky@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 125,
            "name": "LYCEE KAFOUNTINE",
            "slug": "lycee-kafountine",
            "code": "rVtLZeHd",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.kafountine@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 126,
            "name": "LYCEE KARTIACK",
            "slug": "lycee-kartiack",
            "code": "LdLQH2jI",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.kartiack@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 132,
            "name": "LYCEE TENDOUCK",
            "slug": "lycee-tendouck",
            "code": "HT6ruE8C",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.tendouck@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 134,
            "name": "LYCEE THIONCK ESSYL",
            "slug": "lycee-thionck-essyl",
            "code": "u1uGqbPx",
            "ief": 2,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.thionck.essyl@caosp.zig",
            "phone": "33 991 11 59",
            "address": 2,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 113,
            "name": "LYCEE ALINE SITOE DIATTA",
            "slug": "lycee-aline-sitoe-diatta",
            "code": "Iane0tge",
            "ief": 3,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.aline.sitoe.diatta@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 116,
            "name": "LYCEE CABROUSSE",
            "slug": "lycee-cabrousse",
            "code": "8XN86DRR",
            "ief": 3,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.cabrousse@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 127,
            "name": "LYCEE MLOMP OUSSOUYE",
            "slug": "lycee-mlomp-oussouye",
            "code": "N3Ia8rh2",
            "ief": 3,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.mlomp.oussouye@caosp.zig",
            "phone": "33 991 11 59",
            "address": 3,
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 111,
            "name": "LYCEE ADEANE",
            "slug": "lycee-adeane",
            "code": "kLwgvqIk",
            "ief": 4,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.adeane@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 121,
            "name": "LYCEE DJIGNABO",
            "slug": "lycee-djignabo",
            "code": "3v64ZaI6",
            "ief": 4,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.djignabo@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 123,
            "name": "LYCEE ELHADJ OMAR LAMINE BADJI",
            "slug": "lycee-elhadj-omar-lamine-badji",
            "code": "NhSnZv2a",
            "ief": 4,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.elhadj.omar.lamine.badji@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 124,
            "name": "LYCEE INDETERMINE",
            "slug": "lycee-indetermine",
            "code": "YWsqKz3Y",
            "ief": 4,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.indetermine@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 128,
            "name": "LYCEE NIAGUIS",
            "slug": "lycee-niaguis",
            "code": "6GTuTObj",
            "ief": 4,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.niaguis@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        },
        {
            "id": 130,
            "name": "LYCEE PEYRISSAC",
            "slug": "lycee-peyrissac",
            "code": "WxezzPxZ",
            "ief": 4,
            "type_etablissement": "lycee",
            "nomce": "Proviseur LYCEE",
            "email": "lycee.peyrissac@caosp.zig",
            "phone": "33 991 11 59",
            "address": "Ziguinchor",
            "created_at": "2024-01-19T19:46:55",
            "updated_at": "2024-01-19T19:46:55.777",
            "save_by": 1
        }
        ]
        for etab in etablissements:
            
            if superuser == "kisarrweb":
                    
                etablissement = Etablissement.objects.create(
                    name = etab['name'],
                    slug = etab['slug'],
                    code = etab['code'],
                    ief_id = etab['ief'],
                    type_etablissement = etab['type_etablissement'],
                    nomce  = etab['nomce'],
                    email = etab['email'], 
                    phone = etab['phone'],
                    address = etab['address'],
                    save_by_id = etab['save_by']
                )
                self.stdout.write(self.style.SUCCESS(f'Etablissement {etablissement.name} with id {etablissement.id} added successfully!'))
            else:
                pass
        