# Generated by Django 5.0.1 on 2024-01-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnneeScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee",
                    models.CharField(
                        choices=[
                            ("2023-2024", "2023-2024"),
                            ("2024-2025", "2024-2025"),
                            ("2025-2026", "2025-2026"),
                            ("2026-2027", "2026-2027"),
                            ("2027-2028", "2027-2028"),
                            ("2028-2029", "2028-2029"),
                            ("2029-2030", "2029-2030"),
                        ],
                        max_length=9,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "statut",
                    models.CharField(blank=True, default="anneeEnCours", max_length=20),
                ),
            ],
            options={
                "verbose_name": "anneeScolaire",
                "verbose_name_plural": "anneeScolaires",
            },
        ),
    ]
